### ISSUE TITLE
kolors lora train error

### ISSUE THREAD

**Issue by lonngxiang** [modelscope/DiffSynth-Studio#121]
CUDA_VISIBLE_DEVICES="0" python examples/train/kolors/train_kolors_lora.py   --pretrained_unet_path models/kolors/Kolors/unet/diffusion_pytorch_model.safetensors   --pretrained_text_encoder_path models/kolors/Kolors/text_encoder   --pretrained_fp16_vae_path models/sdxl-vae-fp16-fix/diffusion_pytorch_model.safetensors   --dataset_path data/dog   --output_path ./models   --max_epochs 10   --center_crop   --use_gradient_checkpointing   --precision "16-mixed"
Loading checkpoint shards: 100%|████████████████████████████████████| 7/7 [00:00<00:00,  7.61it/s]
Traceback (most recent call last):
  File "/ai/DiffSynth-Studio/examples/train/kolors/train_kolors_lora.py", line 300, in <module>
    model = LightningModel(
  File "/ai/DiffSynth-Studio/examples/train/kolors/train_kolors_lora.py", line 69, in __init__
    self.pipe.vae_encoder = load_model_from_diffsynth(SDXLVAEEncoder, {}, pretrained_fp16_vae_path, torch_dtype, self.device)
  File "/ai/DiffSynth-Studio/examples/train/kolors/train_kolors_lora.py", line 45, in load_model_from_diffsynth
    state_dict = load_state_dict(state_dict_path, torch_dtype=torch_dtype)
  File "/ai/DiffSynth-Studio/diffsynth/models/__init__.py", line 759, in load_state_dict
    return load_state_dict_from_safetensors(file_path, torch_dtype=torch_dtype)
  File "/ai/DiffSynth-Studio/diffsynth/models/__init__.py", line 766, in load_state_dict_from_safetensors
    with safe_open(file_path, framework="pt", device="cpu") as f:
OSError: No such device (os error 19)

**Comment by lonngxiang** [comment]
改成cuda还是不行
with safe_open(file_path, framework="pt", device="cuda") as f:
OSError: No such device (os error 19)

![image](https://github.com/user-attachments/assets/f5ba208c-d01a-444a-bad3-fcd7339d1f58)

**Comment by lonngxiang** [comment]
safetensors               0.4.3 版本

**Comment by lonngxiang** [comment]
transformers              4.43.1

**Comment by lonngxiang** [comment]
![image](https://github.com/user-attachments/assets/313b71bb-422f-467d-91ab-382ee6a2ad33)

**Comment by lonngxiang** [comment]
找到问题了，模型对应目录结构不一致导致
