### ISSUE TITLE
stable diffusion sdxl train error

### ISSUE THREAD

**Issue by CHK-0000** [modelscope/DiffSynth-Studio#253]
(test) C:\DiffSynth-Studio\examples\train\stable_diffusion_xl>python train_sdxl_lora.py --pretrained_path models/stable_diffusion_xl/autismmixSDXL_autismmixConfetti.safetensors --dataset_path C:\DiffSynth-Studio\data\test --output_path ./models --max_epochs 1 --steps_per_epoch 500 --height 1024 --width 1024 --center_crop --precision "32" --learning_rate 1e-4 --lora_rank 4 --lora_alpha 4 --use_gradient_checkpointing
2024-11-01 14:08:11.631651: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-01 14:08:12.397738: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Loading models from: models/stable_diffusion_xl/autismmixSDXL_autismmixConfetti.safetensors
Traceback (most recent call last):
  File "C:\DiffSynth-Studio\examples\train\stable_diffusion_xl\train_sdxl_lora.py", line 54, in <module>
    model = LightningModel(
  File "C:\DiffSynth-Studio\examples\train\stable_diffusion_xl\train_sdxl_lora.py", line 17, in __init__
    model_manager.load_models(pretrained_weights)
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\diffsynth\models\model_manager.py", line 508, in load_models
    self.load_model(file_path, model_names)
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\diffsynth\models\model_manager.py", line 490, in load_model
    if model_detector.match(file_path, state_dict):
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\diffsynth\models\model_manager.py", line 264, in match
    if len(state_dict) == 0:
TypeError: object of type 'NoneType' has no len()

**Comment by hakzarov** [comment]
https://github.com/modelscope/DiffSynth-Studio/issues/470

**Comment by Artiprocher** [comment]
@CHK-0000 It seems that your model did not load correctly. Please provide us with the model's link so that we can investigate the issue.
