### ISSUE TITLE
generate video error, model weight error?

### ISSUE THREAD

**Issue by TigerHH6866** [modelscope/DiffSynth-Studio#30]
Traceback (most recent call last):
  File "/root/miniconda3/envs/DiffSynthStudio/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/root/autodl-tmp/DiffSynth-Studio/pages/2_Video_Creator.py", line 197, in <module>
    SDVideoPipelineRunner(in_streamlit=True).run(config)
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/pipelines/stable_diffusion_video.py", line 340, in run
    model_manager, pipe = self.load_pipeline(**config["models"])
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/pipelines/stable_diffusion_video.py", line 271, in load_pipeline
    model_manager.load_textual_inversions(textual_inversion_folder)
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/models/__init__.py", line 181, in load_textual_inversions
    state_dict = load_state_dict(os.path.join(folder, file_name))
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/models/__init__.py", line 244, in load_state_dict
    return load_state_dict_from_bin(file_path, torch_dtype=torch_dtype)
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/models/__init__.py", line 258, in load_state_dict_from_bin
    state_dict = torch.load(file_path, map_location="cpu")
  File "/root/miniconda3/envs/DiffSynthStudio/lib/python3.9/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/DiffSynthStudio/lib/python3.9/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '-'.

**Comment by Artiprocher** [comment]
In the textual inversion folder, there are some files that are not supported by our code. Please remove them.

**Comment by TigerHH6866** [comment]
> In the textual inversion folder, there are some files that are not supported by our code. Please remove them.

maked sure  textual inversion folder only have verybadimagenegative_v1.3.pt, another error comes


  File "/root/miniconda3/envs/DiffSynthStudio/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/root/autodl-tmp/DiffSynth-Studio/pages/2_Video_Creator.py", line 197, in <module>
    SDVideoPipelineRunner(in_streamlit=True).run(config)
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/pipelines/stable_diffusion_video.py", line 340, in run
    model_manager, pipe = self.load_pipeline(**config["models"])
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/pipelines/stable_diffusion_video.py", line 271, in load_pipeline
    model_manager.load_textual_inversions(textual_inversion_folder)
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/models/__init__.py", line 181, in load_textual_inversions
    state_dict = load_state_dict(os.path.join(folder, file_name))
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/models/__init__.py", line 244, in load_state_dict
    return load_state_dict_from_bin(file_path, torch_dtype=torch_dtype)
  File "/root/autodl-tmp/DiffSynth-Studio/diffsynth/models/__init__.py", line 258, in load_state_dict_from_bin
    state_dict = torch.load(file_path, map_location="cpu")
  File "/root/miniconda3/envs/DiffSynthStudio/lib/python3.9/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/DiffSynthStudio/lib/python3.9/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/DiffSynthStudio/lib/python3.9/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: 'models/textual_inversion/.ipynb_checkpoints'

**Comment by TigerHH6866** [comment]
.ipynb_checkpoints!!! del it and all gooood
