### ISSUE TITLE
Repository Not Found for url: https://huggingface.co/models/Annotators/resolve/main/sk_model.pth.

### ISSUE THREAD

**Issue by goku-kakarot-7227** [modelscope/DiffSynth-Studio#54]
Why am I getting this error? Can someone please help?

Traceback (most recent call last):
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/models/Annotators/resolve/main/sk_model.pth

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/examples/image_synthesis/sd_text_to_image.py", line 21, in <module>
    pipe = SDImagePipeline.from_model_manager(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/diffsynth/pipelines/stable_diffusion.py", line 69, in from_model_manager
    pipe.fetch_controlnet_models(model_manager, controlnet_config_units)
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/diffsynth/pipelines/stable_diffusion.py", line 42, in fetch_controlnet_models
    Annotator(config.processor_id),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/diffsynth/controlnets/processors.py", line 23, in __init__
    self.processor = LineartDetector.from_pretrained(model_path).to("cuda")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/controlnet_aux/lineart/__init__.py", line 108, in from_pretrained
    model_path = hf_hub_download(pretrained_model_or_path, filename, cache_dir=cache_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1823, in _raise_on_head_call_error
    raise head_call_error
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 396, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/goku-kakarot-7227/Desktop/DiffSynth-Studio/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-667bc91f-2e38fd6b79acdb762c1dba9d;c12df456-0cd6-4711-ac97-91c4de0683f8)

Repository Not Found for url: https://huggingface.co/models/Annotators/resolve/main/sk_model.pth.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

**Comment by Artiprocher** [comment]
This error is caused by `controlnet_aux`. To fix it, please download the two files manually:

- `models/Annotators/sk_model.pth`: [link](https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model.pth)
- `models/Annotators/sk_model2.pth`: [link](https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model2.pth)

By the way, we will provide an automatic model downloader instead of using the other packages.

**Comment by goku-kakarot-7227** [comment]
I already downloaded all the files required in "sd_text_to_image.py" including the 2 files you gave the link and placed those files at required positions. But still getting this error. Then I searched for the url [](https://huggingface.co/models/Annotators/resolve/main/sk_model.pth )which is giving error but could not find the exact url in whole project. And when i open this url, I get the same error "Invalid username or password". As the last 2 lines of the error says, 

"Please make sure you specified the correct repo_id and repo_type.
If you are trying to access a private or gated repo, make sure you are authenticated."

Is the url right, or is the hugging face repo shifted elsewhere?

**Comment by goku-kakarot-7227** [comment]
@Artiprocher any suggestions?
