### ISSUE TITLE
Load models into respective folders

### ISSUE THREAD

**Issue by muthuramanm** [modelscope/DiffSynth-Studio#61]
Do we have any simple tricks to load all models to respective folders which needs to run this project?

**Comment by Artiprocher** [comment]
Hi, @muthuramanm . The `downloader` module has been added to the project. In each example, you can use `download_models` to download the models required in the script.

For developers, once you type " in the code, your IDE will show the model list and you can easily choose a model. We will update the model list to support more models.

![image](https://github.com/modelscope/DiffSynth-Studio/assets/35051019/932db705-983f-49ef-b094-23cae300535f)

**Comment by muthuramanm** [comment]
Models downloaded, but not able to use to run the project. Please guide me
![image](https://github.com/modelscope/DiffSynth-Studio/assets/40986310/56354d2b-9c53-4eb9-a9fa-93a2a0983000)

**Comment by muthuramanm** [comment]
It seems, download modules are not working as expected.

ubuntu@ip-172-31-46-161:~/DiffSynth-Studio$ python3 examples/image_synthesis/sdxl_turbo.py
Start downloading models/stable_diffusion_xl_turbo/sd_xl_turbo_1.0_fp16.safetensors
Downloading: 0.00B [00:01, ?B/s]
Traceback (most recent call last):
  File "/home/ubuntu/DiffSynth-Studio/examples/image_synthesis/sdxl_turbo.py", line 11, in <module>
    model_manager.load_models(["models/stable_diffusion_xl_turbo/sd_xl_turbo_1.0_fp16.safetensors"])
  File "/home/ubuntu/DiffSynth-Studio/diffsynth/models/__init__.py", line 593, in load_models
    self.load_model(file_path, lora_alphas=lora_alphas)
  File "/home/ubuntu/DiffSynth-Studio/diffsynth/models/__init__.py", line 551, in load_model
    state_dict = load_state_dict(file_path, torch_dtype=self.torch_dtype)
  File "/home/ubuntu/DiffSynth-Studio/diffsynth/models/__init__.py", line 624, in load_state_dict
    return load_state_dict_from_safetensors(file_path, torch_dtype=torch_dtype)
  File "/home/ubuntu/DiffSynth-Studio/diffsynth/models/__init__.py", line 631, in load_state_dict_from_safetensors
    with safe_open(file_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall

**Comment by muthuramanm** [comment]
Hey @Artiprocher , Do we have any photo editing models?. I mean erase text from photos or adding new text in existing photos. Please suggest your ideas. Thanks
