### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall.

### ISSUE THREAD

**Issue by hyytest** [modelscope/DiffSynth-Studio#76]
aingdiffusion_v12.safetensors has been already in models/stable_diffusion.
mm_sd_v15_v2.ckpt has been already in models/AnimateDiff.
control_v11p_sd15_lineart.pth has been already in models/ControlNet.
sk_model.pth has been already in models/Annotators.
sk_model2.pth has been already in models/Annotators.
control_v11f1e_sd15_tile.pth has been already in models/ControlNet.
verybadimagenegative_v1.3.pt has been already in models/textual_inversion.
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-262120401cdb>", line 1, in <cell line: 1>
    runfile('D:/DiffSynth-Studio/examples/Diffutoon/diffutoon_toon_shading.py', wdir='D:/DiffSynth-Studio/examples/Diffutoon')
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/DiffSynth-Studio/examples/Diffutoon/diffutoon_toon_shading.py", line 100, in <module>
    runner.run(config)
  File "d:\diffsynth-studio\diffsynth\pipelines\stable_diffusion_video.py", line 340, in run
    model_manager, pipe = self.load_pipeline(**config["models"])
  File "d:\diffsynth-studio\diffsynth\pipelines\stable_diffusion_video.py", line 272, in load_pipeline
    model_manager.load_models(model_list, lora_alphas=lora_alphas)
  File "d:\diffsynth-studio\diffsynth\models\__init__.py", line 593, in load_models
    self.load_model(file_path, lora_alphas=lora_alphas)
  File "d:\diffsynth-studio\diffsynth\models\__init__.py", line 551, in load_model
    state_dict = load_state_dict(file_path, torch_dtype=self.torch_dtype)
  File "d:\diffsynth-studio\diffsynth\models\__init__.py", line 624, in load_state_dict
    return load_state_dict_from_safetensors(file_path, torch_dtype=torch_dtype)
  File "d:\diffsynth-studio\diffsynth\models\__init__.py", line 631, in load_state_dict_from_safetensors
    with safe_open(file_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall

**Comment by Artiprocher** [comment]
Maybe two reasons:

* Something wrong in your safetensors file. Please delete it and download it again.
* The LoRA format is not supported in our project.
